# Generated by Django 5.2.7 on 2025-10-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
